#!/usr/bin/env bash
#
# Builds Sources/ into a real .app bundle.
#
# SwiftPM alone produces a bare Mach-O executable, and a SwiftUI app run that way is
# subtly wrong: no Info.plist means no bundle identifier, which means App Transport
# Security has no configuration to read, the Keychain has no service identity, and
# os_log has no subsystem. So SwiftPM compiles, and this script does the bundling —
# which is also the layout `Bundle.main.resourceURL` expects at runtime.
#
# Usage:
#   ./build.sh                        debug build, ad-hoc signed, no sidecar copied
#   ./build.sh --release              optimised
#   ./build.sh --sidecar ../../dist/sidecar
#   ./build.sh --release --universal --sign "Developer ID Application: Example (TEAMID)"
#   ./build.sh --run                  build, then launch with logs on this terminal

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
APP_NAME="Agentic Workspace"
EXECUTABLE="MacShell"
BUNDLE_ID="co.apolitical.agentic.macshell"
VERSION="${MACSHELL_VERSION:-0.1.0}"
BUILD_NUMBER="${MACSHELL_BUILD:-$(date -u +%Y%m%d%H%M)}"
MIN_MACOS="14.0"

usage() {
  cat <<'USAGE'
build.sh [options]

  --release              optimised build (default: debug)
  --universal            arm64 + x86_64 (default: native arch only)
  --sidecar <dir>        copy a built sidecar into Contents/Resources/sidecar
  --dev-sidecar          bundle a development sidecar that runs from this checkout,
                         plus the node on PATH, so the .app works from Finder
  --sign <identity>      Developer ID signing with hardened runtime
  --run                  launch the built app with logs on this terminal
USAGE
}

CONFIGURATION="debug"
SIDECAR_DIR=""
DEV_SIDECAR=0
SIGN_IDENTITY=""
UNIVERSAL=0
RUN_AFTER=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --release)   CONFIGURATION="release"; shift ;;
    --debug)     CONFIGURATION="debug"; shift ;;
    --universal) UNIVERSAL=1; shift ;;
    --run)       RUN_AFTER=1; shift ;;
    --sidecar)   SIDECAR_DIR="${2:?--sidecar needs a directory}"; shift 2 ;;
    --dev-sidecar) DEV_SIDECAR=1; shift ;;
    --sign)      SIGN_IDENTITY="${2:?--sign needs an identity}"; shift 2 ;;
    -h|--help)   usage; exit 0 ;;
    *)           echo "unknown option: $1" >&2; exit 2 ;;
  esac
done

if [[ "$(uname -s)" != "Darwin" ]]; then
  echo "This builds a macOS app bundle and only runs on macOS." >&2
  exit 1
fi

command -v swift >/dev/null || { echo "swift not found. Install Xcode or the Swift toolchain." >&2; exit 1; }

# The Liquid Glass APIs in Sources/MacShell/Surface.swift are macOS 26 SDK symbols.
# `#available` guards the runtime, not the SDK — on an older toolchain they do not
# compile at all, and the error is a wall of "cannot find 'glassEffect' in scope".
# The *runtime* floor stays macOS 14; only the build floor is 26.
SDK_MAJOR="$(xcrun --sdk macosx --show-sdk-version 2>/dev/null | cut -d. -f1)"
if [[ -n "$SDK_MAJOR" && "$SDK_MAJOR" -lt 26 ]]; then
  echo "This needs the macOS 26 SDK (Xcode 26+); found SDK $SDK_MAJOR." >&2
  echo "The app still runs on macOS $MIN_MACOS — the glass paths are availability-gated." >&2
  exit 1
fi

BUILD_FLAGS=(-c "$CONFIGURATION" --package-path "$ROOT")
if [[ "$UNIVERSAL" -eq 1 ]]; then
  # Distribution builds must cover both architectures; a native-arch build is fine
  # for development and roughly twice as fast.
  BUILD_FLAGS+=(--arch arm64 --arch x86_64)
fi

ARCH_NOTE="native"
if [[ "$UNIVERSAL" -eq 1 ]]; then ARCH_NOTE="universal"; fi
echo "==> swift build ($CONFIGURATION, $ARCH_NOTE)"
swift build "${BUILD_FLAGS[@]}"
BIN_PATH="$(swift build "${BUILD_FLAGS[@]}" --show-bin-path)"

APP="$ROOT/build/$APP_NAME.app"
CONTENTS="$APP/Contents"

echo "==> assembling $APP"
rm -rf "$APP"
mkdir -p "$CONTENTS/MacOS" "$CONTENTS/Resources"
cp "$BIN_PATH/$EXECUTABLE" "$CONTENTS/MacOS/$EXECUTABLE"

# Classic four-char type/creator file. Harmless, and some tools still look for it.
printf 'APPL????' > "$CONTENTS/PkgInfo"

# App icon. Generated by Tools/make-icon.sh rather than here: regenerating art on
# every build buys nothing and adds a failure mode to the critical path. Copied
# before signing so it is sealed inside the bundle.
if [[ -f "$ROOT/Resources/AppIcon.icns" ]]; then
  cp "$ROOT/Resources/AppIcon.icns" "$CONTENTS/Resources/AppIcon.icns"
else
  echo "    note: no Resources/AppIcon.icns; run ./Tools/make-icon.sh to generate one." >&2
fi

cat > "$CONTENTS/Info.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleName</key>                 <string>$APP_NAME</string>
  <key>CFBundleDisplayName</key>          <string>$APP_NAME</string>
  <key>CFBundleExecutable</key>           <string>$EXECUTABLE</string>
  <key>CFBundleIdentifier</key>           <string>$BUNDLE_ID</string>
  <key>CFBundlePackageType</key>          <string>APPL</string>
  <key>CFBundleShortVersionString</key>   <string>$VERSION</string>
  <key>CFBundleVersion</key>              <string>$BUILD_NUMBER</string>
  <key>CFBundleIconFile</key>             <string>AppIcon</string>
  <key>CFBundleInfoDictionaryVersion</key><string>6.0</string>
  <key>LSMinimumSystemVersion</key>       <string>$MIN_MACOS</string>
  <key>LSApplicationCategoryType</key>    <string>public.app-category.productivity</string>
  <key>NSHighResolutionCapable</key>      <true/>
  <key>NSHumanReadableCopyright</key>     <string>Apolitical</string>

  <!-- The workspace is served over plain HTTP on the loopback interface. There is no
       transport to secure: the traffic never leaves the machine, and terminating TLS
       on a self-signed loopback certificate would only add a trust-store problem.
       NSAllowsLocalNetworking is the narrow key for exactly this; NSAllowsArbitraryLoads
       would disable ATS for the whole app and must not be used. -->
  <key>NSAppTransportSecurity</key>
  <dict>
    <key>NSAllowsLocalNetworking</key><true/>
    <key>NSExceptionDomains</key>
    <dict>
      <key>localhost</key>
      <dict>
        <key>NSExceptionAllowsInsecureHTTPLoads</key><true/>
      </dict>
    </dict>
  </dict>
</dict>
</plist>
PLIST

if [[ -n "$SIDECAR_DIR" ]]; then
  if [[ ! -d "$SIDECAR_DIR" ]]; then
    echo "--sidecar: not a directory: $SIDECAR_DIR" >&2
    exit 1
  fi
  echo "==> copying sidecar from $SIDECAR_DIR"
  mkdir -p "$CONTENTS/Resources/sidecar"
  cp -R "$SIDECAR_DIR"/. "$CONTENTS/Resources/sidecar/"
  if [[ ! -f "$CONTENTS/Resources/sidecar/server.mjs" && ! -f "$CONTENTS/Resources/sidecar/server.js" ]]; then
    echo "    warning: no server.mjs at the top of the sidecar directory." >&2
    echo "    The app looks for Contents/Resources/sidecar/server.mjs, then server.js." >&2
  fi
  if [[ ! -x "$CONTENTS/Resources/sidecar/node" ]]; then
    echo "    note: no bundled node runtime; the app will fall back to one on disk." >&2
  fi
elif [[ "$DEV_SIDECAR" == "1" ]]; then
  # A development bundle: the entry point runs the sidecar out of this working copy
  # rather than carrying its own copy of the app and its dependency tree.
  #
  # This exists because without it the .app only works when launched from a terminal
  # that has AGENTIC_SIDECAR_PATH and a node on PATH — double-clicking it in Finder
  # gets "Sidecar not bundled", which is not an app you can hand to anyone.
  #
  # It is NOT distributable: it hardcodes an absolute path into someone's home
  # directory, and it breaks the moment the checkout moves. A release build needs the
  # real thing — see the note it prints.
  REPO_ROOT="$(cd "$ROOT/../.." && pwd)"
  SIDECAR_ENTRY="$REPO_ROOT/apps/sidecar/server.mjs"
  if [[ ! -f "$SIDECAR_ENTRY" ]]; then
    echo "--dev-sidecar: no sidecar at $SIDECAR_ENTRY" >&2
    exit 1
  fi
  if [[ ! -f "$REPO_ROOT/apps/web/.next/BUILD_ID" ]]; then
    echo "--dev-sidecar: apps/web has not been built." >&2
    echo "    Run: pnpm --filter @workspace/web build" >&2
    exit 1
  fi
  echo "==> bundling a development sidecar from $REPO_ROOT"
  mkdir -p "$CONTENTS/Resources/sidecar"
  cat > "$CONTENTS/Resources/sidecar/server.mjs" <<DEVSIDECAR
// Generated by build.sh --dev-sidecar. Do not commit; do not distribute.
//
// The real sidecar and the Next build it serves live in the working copy. This file
// exists only so the .app has an entry point at the path SidecarLaunch expects.
import '$SIDECAR_ENTRY'
DEVSIDECAR

  # Finder launches the app with no PATH worth the name, and the fallbacks in
  # resolveNodeExecutable do not include nvm — which is where most Macs actually keep
  # node. Copying the running one in is what makes the Dock work.
  NODE_BIN="$(command -v node || true)"
  if [[ -z "$NODE_BIN" ]]; then
    echo "    warning: no node on PATH to bundle; the app will search its fallbacks." >&2
  else
    NODE_VERSION="$("$NODE_BIN" --version)"
    echo "    bundling node $NODE_VERSION from $NODE_BIN"
    cp "$NODE_BIN" "$CONTENTS/Resources/sidecar/node"
    chmod +x "$CONTENTS/Resources/sidecar/node"
  fi
else
  echo "==> no --sidecar given; set AGENTIC_SIDECAR_PATH to a server entry point when running"
fi

# Signing. On Apple silicon every executable must carry at least an ad-hoc signature
# or the kernel refuses to run it, so there is no unsigned path.
if [[ -n "$SIGN_IDENTITY" ]]; then
  echo "==> signing with: $SIGN_IDENTITY"
  # Inside-out, never --deep: --deep is deprecated, applies the wrong entitlements to
  # nested code, and is the usual cause of a notarization rejection.
  if [[ -x "$CONTENTS/Resources/sidecar/node" ]]; then
    codesign --force --timestamp --options runtime \
      --entitlements "$ROOT/Entitlements/Sidecar.entitlements" \
      --sign "$SIGN_IDENTITY" "$CONTENTS/Resources/sidecar/node"
  fi
  # Any other Mach-O in Resources (native addons, helper binaries) also needs its own
  # signature before the outer bundle is sealed.
  while IFS= read -r -d '' macho; do
    codesign --force --timestamp --options runtime \
      --entitlements "$ROOT/Entitlements/Sidecar.entitlements" \
      --sign "$SIGN_IDENTITY" "$macho"
  done < <(find "$CONTENTS/Resources" -type f \( -name '*.node' -o -name '*.dylib' \) -print0 2>/dev/null || true)

  codesign --force --timestamp --options runtime \
    --entitlements "$ROOT/Entitlements/MacShell.entitlements" \
    --sign "$SIGN_IDENTITY" "$APP"
  codesign --verify --deep --strict --verbose=2 "$APP"
  echo "==> next: notarize with"
  echo "    ditto -c -k --keepParent \"$APP\" build/AgenticWorkspace.zip"
  echo "    xcrun notarytool submit build/AgenticWorkspace.zip --keychain-profile <profile> --wait"
  echo "    xcrun stapler staple \"$APP\""
else
  echo "==> ad-hoc signing (local use only; not distributable)"
  codesign --force --sign - "$APP"
fi

echo "==> built $APP"
# Launch Services caches icons by bundle path, so a rebuilt icon at the same path
# keeps showing the stale one until the registration is refreshed.
/System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/Support/lsregister \
  -f "$APP" >/dev/null 2>&1 || true

if [[ "$RUN_AFTER" -eq 1 ]]; then
  # Executed directly rather than via `open` so stdout, stderr and any crash text
  # land on this terminal. Bundle.main still resolves to the .app, because the
  # binary is inside it.
  echo "==> running"
  exec "$CONTENTS/MacOS/$EXECUTABLE"
fi
